### ISSUE TITLE
Liens cassés

### ISSUE THREAD

**Issue by GuillaumeIfa** [JLdevprog/SpotIFA#29]
Hello,

j'ai cloné ton dépôt dans un dossier, tes liens ne fonctionnent pas, quand je lance ton projet, je n'ai pas d'images et les liens sont morts.

Essaye de faire un git clone dans un dossier (pas à la racine de ton wamp), pour voir ton erreur.

**Comment by JLdevprog** [comment]
ReHello?!

Je viens de Fixer, les chemins.

Merci à Toi et Cédric ;)

**Comment by GuillaumeIfa** [comment]
yes ça fonctionne !
Il manque encore l'image du menu sur l'écran d'accueil

**Comment by JLdevprog** [comment]
Yeahp :'/ ...
Done ;)
